"""initial database migration

Revision ID: fd3b7b38c2bf
Revises: 
Create Date: 2020-08-03 10:40:42.156578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3b7b38c2bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('orderId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fruitName', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('orderId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
